events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       5000;
        server_name  localhost;

        # Node.js UI (FormMate)
        location /mate/ {
            proxy_pass http://127.0.0.1:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Main .NET API (FormCMS)
        location / {
            proxy_pass http://127.0.0.1:5001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Custom Error Page for when .NET is restarting
            error_page 502 = @restarting;
        }
        
        location @restarting {
             add_header Retry-After 3 always;
             return 503 "The system is restarting configuration. Please refresh in a few seconds.";
        }
    }
}
