import { AGENT_NAMES, type PageComponentDefinition } from '@formmate/shared';

// Define the available page components
export const PAGE_COMPONENT_REGISTRY: PageComponentDefinition[] = [
    {
        id: 'common_component',
        agentName: AGENT_NAMES.COMPONENT_BUILDER,
        label: 'Common Component',
        icon: 'Code2', // Using same icon
        color: 'gray',
        pageTypes: [],
        resourceDir: 'common-component',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Modify component',
    },
    {
        id: 'engagement_bar',
        agentName: AGENT_NAMES.PAGE_ENGAGEMENT_BAR_BUILDER,
        label: 'Engagement Bar',
        icon: 'MessageSquarePlus',
        color: 'blue',
        pageTypes: ['detail'],
        resourceDir: 'engagement-bar',
        hasSnippet: true,
        chatMessage: 'Add engagement bar code to this page',
    },
    {
        id: 'user_avatar',
        agentName: AGENT_NAMES.PAGE_USER_AVATAR_BUILDER,
        label: 'User Avatar',
        icon: 'UserCircle',
        color: 'green',
        pageTypes: ['detail', 'list'],
        resourceDir: 'user-avatar',
        hasSnippet: true,
        chatMessage: 'Add user avatar to header',
    },

    {
        id: 'top_list',
        agentName: AGENT_NAMES.PAGE_TOP_LIST_BUILDER,
        label: 'Top List',
        icon: 'TrendingUp',
        color: 'purple',
        pageTypes: ['detail', 'list'],
        resourceDir: 'top-list',
        hasSnippet: true,
        chatMessage: 'Add top list component to this page',
    },
    {
        id: 'search_bar',
        agentName: AGENT_NAMES.PAGE_SEARCH_BAR_BUILDER,
        label: 'Search Bar',
        icon: 'Search',
        color: 'orange',
        pageTypes: ['list'],
        resourceDir: 'search-bar',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add search bar to this page',
    },
    {
        id: 'data_list',
        agentName: AGENT_NAMES.PAGE_DATA_LIST_BUILDER,
        label: 'Data List',
        icon: 'List',
        color: 'teal',
        pageTypes: ['list'],
        resourceDir: 'data-list',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add data list component to this page',
    },
    {
        id: 'pagination',
        agentName: AGENT_NAMES.PAGE_PAGINATION_BUILDER,
        label: 'Pagination',
        icon: 'ChevronsLeftRight',
        color: 'slate',
        pageTypes: ['list'],
        resourceDir: 'pagination',
        hasSnippet: true,
        needQueries: true,
        chatMessage: 'Add cursor-based pagination to this page',
    },
    {
        id: 'breadcrumb',
        agentName: AGENT_NAMES.PAGE_BREADCRUMB_BUILDER,
        label: 'Breadcrumb',
        icon: 'ChevronRight',
        color: 'gray',
        pageTypes: ['detail'],
        resourceDir: 'breadcrumb',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add breadcrumb navigation to this page',
    },
    {
        id: 'detail_hero',
        agentName: AGENT_NAMES.PAGE_DETAIL_HERO_BUILDER,
        label: 'Detail Hero',
        icon: 'Image',
        color: 'indigo',
        pageTypes: ['detail'],
        resourceDir: 'detail-hero',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add hero header section to this page',
    },
    {
        id: 'related_items',
        agentName: AGENT_NAMES.PAGE_RELATED_ITEMS_BUILDER,
        label: 'Related Items',
        icon: 'Layers',
        color: 'amber',
        pageTypes: ['detail'],
        resourceDir: 'related-items',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add related items section to this page',
    },
    {
        id: 'table_view',
        agentName: AGENT_NAMES.PAGE_TABLE_VIEW_BUILDER,
        label: 'Table View',
        icon: 'Table',
        color: 'cyan',
        pageTypes: ['list'],
        resourceDir: 'table-view',
        hasSnippet: false,
        needQueries: true,
        chatMessage: 'Add table view component to this page',
    },
    {
        id: 'contact_form',
        agentName: AGENT_NAMES.PAGE_CONTACT_FORM_BUILDER,
        label: 'Contact Form',
        icon: 'Mail',
        color: 'emerald',
        pageTypes: ['detail', 'list'],
        resourceDir: 'contact-form',
        hasSnippet: true,
        chatMessage: 'Add contact form to this page',
    },
    {
        id: 'image_carousel',
        agentName: AGENT_NAMES.PAGE_IMAGE_CAROUSEL_BUILDER,
        label: 'Image Carousel',
        icon: 'Images',
        color: 'violet',
        pageTypes: ['detail', 'list'],
        resourceDir: 'image-carousel',
        hasSnippet: true,
        needQueries: true,
        chatMessage: 'Add image carousel to this page',
    },
    {
        id: 'faq_accordion',
        agentName: AGENT_NAMES.PAGE_FAQ_ACCORDION_BUILDER,
        label: 'FAQ Accordion',
        icon: 'HelpCircle',
        color: 'rose',
        pageTypes: ['detail', 'list'],
        resourceDir: 'faq-accordion',
        hasSnippet: true,
        needQueries: true,
        chatMessage: 'Add FAQ accordion section to this page',
    },
];
