//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface PublicUserInfo {
    id: string;
    name: string;
    avatarUrl: string;
}

export interface Notification {
    userId: string;
    senderId: string;
    actionType: string;
    messageType: string;
    message: string;
    url: string;
    isRead: boolean;
    id: number;
    createdAt: Date;
    sender: PublicUserInfo | undefined;
}