import { AGENT_NAMES, type PageAddonDefinition } from '@formmate/shared';

export const PAGE_ADDON_REGISTRY: PageAddonDefinition[] = [
    {
        id: 'engagement_bar',
        agentName: AGENT_NAMES.PAGE_ENGAGEMENT_BAR_BUILDER,
        label: 'Engagement Bar',
        icon: 'MessageSquarePlus',
        color: 'blue',
        pageTypes: ['detail'],
        metadataFlag: 'enableEngagementBar',
        resourceDir: 'engagement-bar',
        hasSnippet: true,
        chatMessage: 'Add engagement bar code to this page',
    },
    {
        id: 'user_avatar',
        agentName: AGENT_NAMES.PAGE_USER_AVATAR_BUILDER,
        label: 'User Avatar',
        icon: 'UserCircle',
        color: 'green',
        pageTypes: ['detail', 'list'],
        metadataFlag: 'enableUserAvatar',
        resourceDir: 'user-avatar',
        hasSnippet: true,
        chatMessage: 'Add user avatar to header',
    },
    {
        id: 'visit_tracker',
        agentName: AGENT_NAMES.PAGE_VISIT_TRACKER,
        label: 'Visit Tracking',
        icon: 'Eye',
        color: 'orange',
        pageTypes: ['detail', 'list'],
        metadataFlag: 'enableVisitTrack',
        resourceDir: 'visit-tracker',
        hasSnippet: false,
        chatMessage: 'Add visit tracking to this page',
    },
    {
        id: 'top_list',
        agentName: AGENT_NAMES.PAGE_TOP_LIST_BUILDER,
        label: 'Top List',
        icon: 'TrendingUp',
        color: 'purple',
        pageTypes: ['detail', 'list'],
        metadataFlag: 'enableTopList',
        resourceDir: 'top-list',
        hasSnippet: true,
        chatMessage: 'Add top list component to this page',
    },
];
