//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface Price {
    id: string;
    name: string;
    currency: string;
    amount: number;
    description: string;
    interval: string;
    nextBillingDate: Date | undefined;
}